### PR TITLE
add ability to pass in options to findByConditions and findAll

### PR DESCRIPTION
**Pull request by JakeTompkins**

### CODE REVIEW

**Review by JandenMa — COMMENTED** [review]
Alright, what exactly does it for? Imo, I think it will be better if we use object parameter and deconstruct it, because we don't need to worry about the params order.

**Comment by JakeTompkins** [comment]
> Alright, what exactly does it for? Imo, I think it will be better if we use object parameter and deconstruct it, because we don't need to worry about the params order.

There currently isn't any way to pass sortBy, offset etc through findByConditions and into the SingleQueryExecutor, so if we want to be able to use that feature we need to build out a completely separate function or add unnecessary logic to determine if the model calls findByConditions or SingleQueryExecutor.

If you want to change the pglink model to take object parameters I'm all for it, I was just doing it this way because it's how the package is written. That's up to you.

**Comment by JandenMa** [comment]
> > Alright, what exactly does it for? Imo, I think it will be better if we use object parameter and deconstruct it, because we don't need to worry about the params order.
> 
> There currently isn't any way to pass sortBy, offset etc through findByConditions and into the SingleQueryExecutor, so if we want to be able to use that feature we need to build out a completely separate function or add unnecessary logic to determine if the model calls findByConditions or SingleQueryExecutor.
> 
> If you want to change the pglink model to take object parameters I'm all for it, I was just doing it this way because it's how the package is written. That's up to you.

Gotcha. Seems we have to do that way because it is a little stupid to pass undefined to those params we don't need.

**Review by JandenMa — APPROVED** [review]
Seems not bad to me.

**Pull request merged**
