### PR TITLE
added an option to skip committing the client in Transaction

### PR DESCRIPTION
**Pull request by JakeTompkins**
Let me know if this interferes with your client management @JandenMa . I'm fairly certain it won't but want to make sure.

### CODE REVIEW

**Comment by JandenMa** [comment]
I dont think it will interfere with my client management. however we should consider about that if devs couldnt use it correctly, is there any memory leak issue? @JakeTompkins

**Comment by JakeTompkins** [comment]
I changed the wording of the parameter and added an explanation in the readme. Should make it harder to mess up.

**Comment by JandenMa** [comment]
> I changed the wording of the parameter and added an explanation in the readme. Should make it harder to mess up.

Could you show me a scenario about it?

**Comment by JakeTompkins** [comment]
`static async getHistories({ companyId, client }) {
    const dao = new BaseModel({
      defaultPermission: {
        authFields: ['companyId'],
        scope: 'COMPANY'
      }
    });

    const liveCheckSql = `
      SELECT "checkNo"
      FROM live_checks
      WHERE "companyId" = $1
    `;

    const pscSql = `
      SELECT "checkNo"
      FROM pressure_sealed_checks
      WHERE "companyId" = $1
    `;

    const replacements = [companyId];

    const liveCheckNumbers = await dao.dataAccess.Transaction({
      params: [{ sql: liveCheckSql, replacements }],
      client
    });
    const pscCheckNumbers = await dao.dataAccess.Transaction({
      params: [{ sql: pscSql, replacements }],
      client
    });

    const checkNos = [...liveCheckNumbers, ...pscCheckNumbers].map(
      (res) => res.checkNo
    );

    return checkNos;
  }`

This is in a class that's used in a before action. I need to be able to run the transactions with the provided client because they need access to data that hasn't been committed yet, but I can't have them commit the transaction when they finish because the main method needs to use the client. Adding a callback isn't really a good option because it's a before action, so I need a way to prevent Transaction from committing at the end

**Comment by JandenMa** [comment]
> `static async getHistories({ companyId, client }) {
> const dao = new BaseModel({
> defaultPermission: {
> authFields: ['companyId'],
> scope: 'COMPANY'
> }
> });
> 
> ```
> const liveCheckSql = `
>   SELECT "checkNo"
>   FROM live_checks
>   WHERE "companyId" = $1
> `;
> 
> const pscSql = `
>   SELECT "checkNo"
>   FROM pressure_sealed_checks
>   WHERE "companyId" = $1
> `;
> 
> const replacements = [companyId];
> 
> const liveCheckNumbers = await dao.dataAccess.Transaction({
>   params: [{ sql: liveCheckSql, replacements }],
>   client
> });
> const pscCheckNumbers = await dao.dataAccess.Transaction({
>   params: [{ sql: pscSql, replacements }],
>   client
> });
> 
> const checkNos = [...liveCheckNumbers, ...pscCheckNumbers].map(
>   (res) => res.checkNo
> );
> 
> return checkNos;
> ```
> 
> }`
> 
> This is in a class that's used in a before action. I need to be able to run the transactions with the provided client because they need access to data that hasn't been committed yet, but I can't have them commit the transaction when they finish because the main method needs to use the client. Adding a callback isn't really a good option because it's a before action, so I need a way to prevent Transaction from committing at the end

alright i got it. however did you consider about if other function passes client in, even if you should call before action?

**Comment by JakeTompkins** [comment]
> > `static async getHistories({ companyId, client }) {
> > const dao = new BaseModel({
> > defaultPermission: {
> > authFields: ['companyId'],
> > scope: 'COMPANY'
> > }
> > });
> > ```
> > const liveCheckSql = `
> >   SELECT "checkNo"
> >   FROM live_checks
> >   WHERE "companyId" = $1
> > `;
> > 
> > const pscSql = `
> >   SELECT "checkNo"
> >   FROM pressure_sealed_checks
> >   WHERE "companyId" = $1
> > `;
> > 
> > const replacements = [companyId];
> > 
> > const liveCheckNumbers = await dao.dataAccess.Transaction({
> >   params: [{ sql: liveCheckSql, replacements }],
> >   client
> > });
> > const pscCheckNumbers = await dao.dataAccess.Transaction({
> >   params: [{ sql: pscSql, replacements }],
> >   client
> > });
> > 
> > const checkNos = [...liveCheckNumbers, ...pscCheckNumbers].map(
> >   (res) => res.checkNo
> > );
> > 
> > return checkNos;
> > ```
> > 
> > 
> > }`
> > This is in a class that's used in a before action. I need to be able to run the transactions with the provided client because they need access to data that hasn't been committed yet, but I can't have them commit the transaction when they finish because the main method needs to use the client. Adding a callback isn't really a good option because it's a before action, so I need a way to prevent Transaction from committing at the end
> 
> alright i got it. however did you consider about if other function passes client in, even if you should call before action?

Sorry, I'm not sure I understand the question

**Comment by JandenMa** [comment]
> > > `static async getHistories({ companyId, client }) {
> > > const dao = new BaseModel({
> > > defaultPermission: {
> > > authFields: ['companyId'],
> > > scope: 'COMPANY'
> > > }
> > > });
> > > ```
> > > const liveCheckSql = `
> > >   SELECT "checkNo"
> > >   FROM live_checks
> > >   WHERE "companyId" = $1
> > > `;
> > > 
> > > const pscSql = `
> > >   SELECT "checkNo"
> > >   FROM pressure_sealed_checks
> > >   WHERE "companyId" = $1
> > > `;
> > > 
> > > const replacements = [companyId];
> > > 
> > > const liveCheckNumbers = await dao.dataAccess.Transaction({
> > >   params: [{ sql: liveCheckSql, replacements }],
> > >   client
> > > });
> > > const pscCheckNumbers = await dao.dataAccess.Transaction({
> > >   params: [{ sql: pscSql, replacements }],
> > >   client
> > > });
> > > 
> > > const checkNos = [...liveCheckNumbers, ...pscCheckNumbers].map(
> > >   (res) => res.checkNo
> > > );
> > > 
> > > return checkNos;
> > > ```
> > > 
> > > 
> > > }`
> > > This is in a class that's used in a before action. I need to be able to run the transactions with the provided client because they need access to data that hasn't been committed yet, but I can't have them commit the transaction when they finish because the main method needs to use the client. Adding a callback isn't really a good option because it's a before action, so I need a way to prevent Transaction from committing at the end
> > 
> > 
> > alright i got it. however did you consider about if other function passes client in, even if you should call before action?
> 
> Sorry, I'm not sure I understand the question

for example, classA has fnA, and fnA is used in before action. and classB has fnB, and fnA is as callback fn in fnB, and fnA get client from fnB.

**Comment by JakeTompkins** [comment]
If I'm understanding the scenario correctly, I don't think that's a problem since the before action and the callback are different calls to fnA

**Comment by JandenMa** [comment]
> If I'm understanding the scenario correctly, I don't think that's a problem since the before action and the callback are different calls to fnA

alright could you update README?

**Comment by JakeTompkins** [comment]
I added the parameter to Transaction and wrote a note in the readme. Is there anything else you'd like updated?

**Comment by JandenMa** [comment]
> I added the parameter to Transaction and wrote a note in the readme. Is there anything else you'd like updated?

uh sorry miss sth. alright will merge later.

**Review by JandenMa — APPROVED** [review]

**Pull request merged**
